included:
  - Meshtastic/
excluded:
  - Meshtastic/BLE/Proto
line_length:
  warning: 240
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
